with open('numar.txt','r') as f :
    n=f.readline()
with open ('inmultire.txt', 'w') as f:
    f.write(n+ "*1=" + str(int(n)*1))
    f.write('\n')
    f.write(n+ "*2=" + str(int(n)*2))
    f.write('\n')
    f.write(n+ "*3=" + str(int(n)*3))
    f.write('\n')
    f.write(n+ "*4=" + str(int(n)*4))
    f.write('\n')
    f.write(n+ "*5=" + str(int(n)*5))
    f.write('\n')
    f.write(n+ "*6=" + str(int(n)*6))
    f.write('\n')
    f.write(n+ "*7=" + str(int(n)*7))
    f.write('\n')
    f.write(n+ "*8=" + str(int(n)*8))
    f.write('\n')
    f.write(n+ "*9=" + str(int(n)*9))
    f.write('\n')
    f.write(n+ "*10=" + str(int(n)*10))
